/**
 * Motivational lines shown on the home screen.
 * Each item: [title, supporting sentence]
 * Kept bilingual so language switching does not reshuffle meaning.
 */
window.NAFS_MOTIVATIONS = {
  ru: [
    ["Маленькая победа над собой.", "Большие перемены начинаются с одного честного выбора."],
    ["Связаться с разработчиком, instagram - @musafir_dakaev"],
    ["Это очень редкий текст, ты еще не скоро его увидишь"],
    ["Остановись на один вдох.", "Иногда одной паузы достаточно, чтобы вернуть себе выбор."],
    ["Ты сильнее мгновения.", "Желание проходит. Твоё решение остаётся."],
    ["Не идеально. Осознанно.", "Сегодня важна не безошибочность, а возвращение к себе."],
    ["Выбери то, что останется.", "Короткое удовольствие не должно решать за твоё будущее."],
    ["Тишина тоже действие.", "Не каждый импульс заслуживает твоего ответа."],
    ["Один выбор — уже путь.", "Не жди большого подвига. Начни с ближайшего решения."],
    ["Сначала намерение.", "Напомни себе, ради чего ты хочешь устоять."],
    ["Мягко, но твёрдо.", "Не ругай себя. Просто снова возьми направление."],
    ["Ты можешь не спешить.", "Импульс торопит. Осознанность даёт время."],
    ["Вернись в этот момент.", "Прошлую уступку не изменить, следующий выбор ещё твой."],
    ["Победа любит тишину.", "Не обязательно рассказывать. Достаточно сделать."],
    ["Сложно — не значит невозможно.", "Сопротивление часто появляется рядом с ростом."],
    ["Сохрани своё утро.", "Первый осознанный выбор задаёт тон всему дню."],
    ["Не корми привычку.", "То, чему ты уступаешь часто, становится сильнее."],
    ["Будь честен и продолжай.", "Честная отметка полезнее красивой статистики."],
    ["Твоё «нет» имеет вес.", "Каждый отказ от лишнего укрепляет свободу."],
    ["Не спорь с импульсом.", "Заметь его, дай пройти и выбери сам."],
    ["Сделай легче будущему себе.", "Поступи сейчас так, чтобы потом поблагодарить себя."],
    ["Сегодня достаточно одного.", "Одна настоящая победа важнее десяти обещаний."],
    ["Дисциплина — это забота.", "Ты ограничиваешь не себя, а то, что управляет тобой."],
    ["Сила растёт незаметно.", "Каждое маленькое удержание складывается в характер."],
    ["Не начинай сначала.", "Ты уже в пути. Просто продолжи с этого места."],
    ["Дай желанию имя.", "Когда ты видишь импульс ясно, он теряет часть власти."],
    ["Пауза возвращает свободу.", "Между желанием и действием всегда есть пространство."],
    ["Смотри дальше минуты.", "Как этот выбор будет ощущаться вечером?"],
    ["Ты не обязан соглашаться.", "Мысль и желание — ещё не команда."],
    ["Спокойствие сильнее рывка.", "Устойчивая маленькая практика меняет больше героизма."],
    ["Выбери уважение к себе.", "Сдержать слово самому себе — особая форма достоинства."],
    ["Пусть будет трудно.", "Дискомфорт не опасен. Иногда он просто цена роста."],
    ["Не считай уступку концом.", "Она лишь точка данных, а не приговор."],
    ["Намерение живёт в поступке.", "То, что важно, становится видимым через выбор."],
    ["Освободи внимание.", "Не отдавай весь день одному мимолётному желанию."],
    ["Держи направление.", "Скорость может меняться. Курс остаётся твоим."],
    ["Сначала самое верное.", "Удобное можно сделать потом. Важное — сейчас."],
    ["Ты уже заметил.", "Осознание импульса — половина победы."],
    ["Сделай шаг меньше.", "Если трудно отказаться навсегда, откажись на десять минут."],
    ["Ничего не доказывай.", "Эта победа нужна не людям, а твоему сердцу."],
    ["Пусть выбор будет чистым.", "Без стыда за прошлое и гордости за счёт."],
    ["Начни с благодарности.", "Когда достаточно уже есть, лишнее теряет силу."],
    ["Береги внутренний порядок.", "Не каждое желание заслуживает места в твоём дне."],
    ["Свобода требует практики.", "Каждый раз, когда выбираешь сам, она становится крепче."],
    ["Удержаться — тоже движение.", "Не делать лишнего иногда важнее нового действия."],
    ["Сделай выбор один раз.", "Не возвращайся к торгу после принятого решения."],
    ["Будь рядом с собой.", "Не бросай себя именно в тот момент, когда стало трудно."],
    ["День ещё не закончен.", "Баланс можно изменить следующим честным выбором."],
    ["Терпение имеет форму.", "Сегодня оно может быть одним спокойным «нет»."],
    ["Смотри без осуждения.", "Ясность помогает меняться лучше, чем стыд."],
    ["Твоё внимание — аманат.", "Отдавай его тому, что действительно имеет значение."],
    ["Пусть сердце ведёт.", "Не позволяй самому громкому желанию стать главным."],
    ["СубханаЛлах.", "Очисти сердце от шума желания."],
    ["АльхамдулиЛлах.", "Благодарность ослабляет хватку нафса."],
    ["Аллахуакбар.", "То, что тянет тебя, меньше Него."],
    ["ЛяИляхаИлляЛлах.", "Верни сердце к Единому."],
    ["АстагфируЛлах.", "Срыв не конец. Вернись."],
    ["Ля Хавля Ва Ля Куввата Илля Би Ллах.", "Сила — не в борьбе в одиночку."],
    ["СубханаЛлахи Ва Бихамдихи.", "Лёгкий зикр — крепкий щит."],
    ["АстагфируЛлах аль Азым.", "Попроси прощение сейчас — и продолжай путь."],
  ],
  en: [
    ["A small victory over yourself.", "Big change begins with one honest choice."],
    ["Pause for one breath.", "Sometimes a single pause is enough to reclaim the choice."],
    ["You are stronger than the moment.", "Desire passes. Your decision remains."],
    ["Not perfect. Aware.", "Today is not about flawlessness. It is about returning to yourself."],
    ["Choose what will last.", "A short pleasure should not decide your future."],
    ["Silence is also an action.", "Not every impulse deserves your answer."],
    [
      "One choice is already a path.",
      "Do not wait for a grand feat. Start with the nearest decision.",
    ],
    ["Intention first.", "Remind yourself why you want to hold steady."],
    ["Gentle, but firm.", "Do not scold yourself. Just take the direction again."],
    ["You do not have to rush.", "Impulse hurries. Awareness gives time."],
    ["Come back to this moment.", "A past slip cannot be changed. The next choice is still yours."],
    ["Victory loves quiet.", "You do not have to announce it. Doing it is enough."],
    ["Hard does not mean impossible.", "Resistance often appears right next to growth."],
    ["Protect your morning.", "The first conscious choice sets the tone for the whole day."],
    ["Do not feed the habit.", "What you yield to often becomes stronger."],
    ["Be honest and continue.", "An honest mark is more useful than pretty statistics."],
    ["Your “no” has weight.", "Every refusal of the unnecessary strengthens freedom."],
    ["Do not argue with the impulse.", "Notice it, let it pass, and choose yourself."],
    ["Make it easier for your future self.", "Act now in a way you will thank yourself for later."],
    ["One is enough today.", "One real victory matters more than ten promises."],
    ["Discipline is care.", "You are not limiting yourself. You are limiting what controls you."],
    ["Strength grows quietly.", "Each small hold builds character."],
    ["Do not start over.", "You are already on the path. Continue from here."],
    ["Name the desire.", "When you see an impulse clearly, it loses some of its power."],
    ["A pause returns freedom.", "Between desire and action there is always space."],
    ["Look past the minute.", "How will this choice feel tonight?"],
    ["You do not have to agree.", "A thought or desire is not a command."],
    ["Calm beats a sprint.", "A steady small practice changes more than heroics."],
    ["Choose self-respect.", "Keeping a promise to yourself is a rare form of dignity."],
    ["Let it be hard.", "Discomfort is not danger. Sometimes it is simply the price of growth."],
    ["Do not treat a slip as the end.", "It is a data point, not a verdict."],
    ["Intention lives in action.", "What matters becomes visible through choice."],
    ["Free your attention.", "Do not give the whole day to one passing desire."],
    ["Hold your direction.", "Speed can change. The course remains yours."],
    ["Do the truest thing first.", "Comfortable can wait. Important belongs to now."],
    ["You already noticed.", "Seeing the impulse is half the victory."],
    ["Take a smaller step.", "If forever feels impossible, refuse it for ten minutes."],
    ["Prove nothing.", "This victory is not for other people. It is for your heart."],
    ["Let the choice be clean.", "No shame for the past. No pride over the score."],
    ["Start with gratitude.", "When enough is already here, excess loses power."],
    ["Guard your inner order.", "Not every desire deserves a place in your day."],
    ["Freedom needs practice.", "Each time you choose yourself, it grows stronger."],
    [
      "Holding back is also movement.",
      "Not doing the extra thing can matter more than a new action.",
    ],
    ["Choose once.", "Do not reopen the bargain after the decision is made."],
    ["Stay with yourself.", "Do not abandon yourself in the exact moment it gets hard."],
    ["The day is not over.", "The next honest choice can still change the balance."],
    ["Patience has a shape.", "Today it may look like one calm “no”."],
    ["Look without judgment.", "Clarity helps change more than shame does."],
    ["Your attention is a trust.", "Give it to what truly matters."],
    ["Let the heart lead.", "Do not let the loudest desire become the main one."],
    ["SubhanaLlah.", "Clear the heart of desire’s noise."],
    ["AlhamduliLlah.", "Gratitude loosens the grip of nafs."],
    ["Allahuakbar.", "What pulls you is smaller than Him."],
    ["LaIlahaIllaLlah.", "Return the heart to the One."],
    ["AstaghfiruLlah.", "A slip is not the end. Return."],
    ["La Hawla Wa La Quwwata Illa Bi Llah.", "Strength is not in fighting alone."],
    ["SubhanAllahi Wa Bihamdihi.", "A light dhikr is a strong shield."],
    ["AstaghfiruLlah al Azeem.", "Ask forgiveness now — and keep walking."],
  ],
};

/** Short dhikr shown right after marking Iman or Nafs. */
window.NAFS_MARK_DHIKR = {
  ru: {
    iman: [
      ["АльхамдулиЛлах", "Хвала Аллаху."],
      ["СубханаЛлах", "Слава Аллаху."],
    ],
    nafs: ["АстагфируЛлах", "Попроси прощение у Аллаха."],
  },
  en: {
    iman: [
      ["AlhamduliLlah", "All praise is for Allah."],
      ["SubhanaLlah", "Glory be to Allah."],
    ],
    nafs: ["AstaghfiruLlah", "Ask Allah for forgiveness."],
  },
};
